package clients.calculator;

/**
 * <H1>Controller for the Calculator</H1>
 * Ferries the information between the model and view
 * @author Brad
 *
 */

public class CalculatorController {
	
	private CalculatorModel model;
	private CalculatorView view;
	
	/**
	 * Construct the controller 
	 * @param model the Calculator model assigned
	 * @param view the Calculator view assigned
	 */
	public CalculatorController(CalculatorModel model, CalculatorView view) {
		//on initialisation assign model and controller
		this.model = model;
		this.view = view;
		
		view.setController(this);
		model.setController(this);
	}
	
	/**
	 * Called by the view, transfers below parameters to the model each pertaining to a patient
	 * All values are transferred as Strings
	 * 
	 * @param fn first name 
	 * @param ln last name 
	 * @param n NHS number 
	 * @param dob Date of birth
	 * @param r Respiration
	 * @param sp02 Sp02
	 * @param sp02s Sp02 Scale
	 * @param o Air or Oxygen
	 * @param bp Blood pressure
	 * @param p Pulse
	 * @param c Consciousness
	 * @param t Temperature
	 * @param i Initials
	 */
	public void doSubmit(String fn, String ln, String n, String dob, String r, String sp02, boolean sp02s, String o, String bp, String p, String c, String t, String i) {
		model.doSubmit(fn, ln, n, dob, r, sp02, sp02s, o, bp, p, c, t, i);	
	}
	
	/**
	 * Takes in a String generated by the model 
	 * 
	 * @param report A report of which contains the fields that are invalid
	 */
	public void doError(String report) {
		view.doError(report);
	}
	

	
}
